CREATE OR REPLACE FUNCTION F_VERIFICA_DATA() RETURNS TRIGGER 
AS 
$$
BEGIN 
	IF NEW.DATA > current_date THEN 
		RAISE 'Não foi possível realizar o cadastro, INSIRA UMA DATA VÁLIDA!';
	END IF;
RETURN NEW;
END;
$$ 
LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TRIGGER_VERIFICA_DATA
BEFORE INSERT OR UPDATE ON CIRURGIA
FOR EACH ROW EXECUTE PROCEDURE F_VERIFICA_DATA();
